### ISSUE TITLE
Remove the "Feedback" link on the top nav

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1069]
##### Description
Currently, we have 2 repeated "Feedback" links one located on the top nav, another one on the footer. We are adding a new "feedback" link on the banner here, see design here: [#1065 Feedback Solicitation for New Team Plan](https://github.com/codecov/engineering-team/issues/1065). 

## Possible solution
To avoid confusion, we should remove the "Feedback" link on the top nav.

**Comment by RulaKhaled** [comment]
@Adal3n3 Can we add a screenshot of the current top nav bar that includes the feedback link please?
