### ISSUE TITLE
[API] Update owner query fields to handle unauthenticated requests

### ISSUE THREAD

**Issue by RulaKhaled** [codecov/engineering-team#1082]
**Problem**
 we're exposing most owner fields in graphql endpoint, which led to exposing sensitive information like org upload token to unauthenticated users 

**Solution**
1-Identify sensitive fields and 2- update resolvers to check if current user is authenticated 

Tip: add a require_auth and let base interactor do the job, override fields that don't need authentication by setting it to false in resolver layer 

More context: 
https://sentry.slack.com/archives/C04L2RSEY3H/p1706017571565589

**Comment by JerrySentry** [comment]
https://www.notion.so/sentry/GraphQL-Owner-Type-Sensitive-Fields-f78cb53e77e4428aa6e04b2819d67884
