### ISSUE TITLE
RCB: Use "indirect" instead of “unexpected_changes”

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1131]
##### Description
This task is a part of the work from RCB v2 https://github.com/codecov/engineering-team/issues/1020

This change only apply on the backend.

#### Action Checklist for Issue Creation
- [ ] Add the design project (to the right under "projects" > settings icon > select "design team")
- [ ] Share in relevant Slack channel (#discuss-codecov-product-design) for visiblity
- [ ] Add targeted launch date/delivery date as/if needed

**Comment by Adal3n3** [comment]
@giovanni-guidini Just to confirm, is this completed? Can I close this issue?

**Comment by Gguidini** [comment]
I believe so
