### ISSUE TITLE
Track adoption of the CLI vs node uploader for coverage uploads

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1182]
**Is your feature request related to a problem? Please describe.**
Help measure progress of CLI adoption - this will help us diagnose what further improvements we need to make to help users adopt the CLI which also helps them adopt new features from Codecov.

**Describe the solution you'd like**
Grafana/Metabase/Looker/Sentry dashboard with the following data

- % of repos that are uploading from CLI
- % repos that are uploading from uploader (node)
- % repos that are uploading from uploader (bash)

Top level filter for public and private repos

**Comment by tnt-sentry** [comment]
There are sentry metrics for this.
