### ISSUE TITLE
[API] Add Component type for Repository.components to retrieve measurements of each component

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1360]
Make sure to add branch filtering and sorting options for (`orderingDirection` and `ordering`) by the four fields in `Component` (name, percentCovered, percentChanged, lastUploaded)

**Comment by RulaKhaled** [comment]
Also add ComponentsFilters which filters by both:
- Components terms
- Branch

```
  filters: {
    components: string[]
    branch: string
  }
```
