### ISSUE TITLE
Create `useRepoComponents` hook to be fetch component measurement booleans

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1369]
- refactor useRepoBackfilled to be a more generic useRepoBackfilled(type)
- in the actual GQL query it will retrieve flags or components based on the type

Similar to `useRepoBackfilled` from Flags, this will return the booleans values related to measurements but for Components.
- isTimescaleEnabled
- componentsMeasurementsActive
- componentsMeasurementsBackfilled
- componentsCount (if we decide to go with this)

Note: for now don't have Components tab use this, we will use it later.
```[tasklist]
### Blocked By
- [ ] https://github.com/codecov/engineering-team/issues/1359
- [ ] https://github.com/codecov/engineering-team/issues/1358
- [ ] https://github.com/codecov/engineering-team/issues/1368
```

**Comment by RulaKhaled** [comment]
1. Let's create a new hook for this one so we're not fetching flags too, let's call it useRepoComponents and fetch:
    - isTimescaleEnabled
    - componentsMeasurementsActive
    - componentsMeasurementsBackfilled
    - componentsCount (if we decide to go with this)

2. Let's add componentsMeasurementsActive resolver in the task list, as we will need this resolver here.
