### ISSUE TITLE
Refactor `useActivateFlagMeasurements` to be generic that takes in measurement type

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1374]
- refactor `useActivateFlagMeasurements` to be a more generic `useActivateMeasurements(type)`

Note: for now update Flags and Components tab to both use `useActivateMeasurements(FLAG_COVERAGE)` because we're not ready to activate COMPONENT_COVERAGE for this tab yet.

**Comment by RulaKhaled** [comment]
I think this does not depend on #1358 so let's remove it from the tasklist
