### ISSUE TITLE
Create `useRepoComponents` hook to query Component measurements

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1377]
This hook will use GQL `Repository.components` to fetch the measurement details.
Note: Don't update component tab to use this yet, will do so later.

```[tasklist]
### Blocked By
- [ ] https://github.com/codecov/engineering-team/issues/1360
```

**Comment by RulaKhaled** [comment]
hmm i think we can close this issue, #1373 does the job

**Comment by RulaKhaled** [comment]
Let's create a new hook instead of refactoring this so we're not fetching flags where we don't need it.
