### ISSUE TITLE
Show last uploaded for each component in the table

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1380]
blocked by: [1379](https://github.com/codecov/engineering-team/issues/1379)

**Comment by RulaKhaled** [comment]
We also need `change` column

**Comment by JerrySentry** [comment]
the `change` column is just the `percentChange` GQL field as currently displayed with the Trend label on the table.

**Comment by RulaKhaled** [comment]
But we're adding it as a separate column in the components table right?
