### ISSUE TITLE
Scope out ability to pin to only new users

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1387]
https://github.com/codecov/engineering-team/issues/1058#issuecomment-1967406368

continue investigation and if needed. Scope out ability to pin this functionality to new users only. This will be implemented by another engineer.

**Comment by giovanni-guidini** [comment]
This is a plan to avoid emitting statuses to the provider. It should address https://github.com/codecov/engineering-team/issues/1078

Notifications for statuses and the PR comment are selected ([here](https://github.com/codecov/worker/blob/6bf962c9f2c9a1f00252a43341aed7d60c52b494/services/notification/__init__.py#L206)) based on the YAML definition.

If we backtrack from the `Notify` task we see that the YAML is a `UserYaml` (see [here](https://github.com/codecov/worker/blob/6bf962c9f2c9a1f00252a43341aed7d60c52b494/tasks/notify.py#L178-L182)).

The final YAML, as the function indicates, is a deep merge of many possible configurations (including the real default config [defined at the install level](https://github.com/codecov/shared/blob/1ebaf3b2228473fa9623678144a164f04bf22ec9/shared/yaml/user_yaml.py#L129)). Our own default config at this time includes `project` and `patch` statuses (see [here](https://github.com/codecov/shared/blob/1ebaf3b2228473fa9623678144a164f04bf22ec9/shared/config/__init__.py#L34)) - the `changes` option is already opt-in.


I believe that it would suffice to alter the `default config` option remove the project status.
I'd do that in the `UserYaml.get_final_yaml` function, by passing the `Repository.created_at` value and having a hard cut-off based on that (a "new customer" then is a repository onboarded after some date where we expect to launch this change).

It's also interesting to pass the owner's plan to this function to avoid override of statuses depending on the user's plan.

So it could look something like
```python
resulting_yaml = get_config("site", default={})
if ownerid is not None and get_config("additional_user_yamls", default={}):
   additional_yaml = _get_possible_additional_user_yaml(ownerid)
   resulting_yaml = merge_yamls(resulting_yaml, additional_yaml)
   
resulting_yaml = _fix_yaml_defaults_based_on_onboarding_time(resulting_yaml, owner.created_at)

if owner_yaml is not None:
   resulting_yaml = merge_yamls(resulting_yaml, owner_yaml)
if commit_yaml is not None:
   resulting_yaml =  merge_yamls(resulting_yaml, commit_yaml)
elif repo_yaml is not None:
   resulting_yaml =  merge_yamls(resulting_yaml, repo_yaml)
   
resulting_yaml = _prevent_overrides_based_on_user_plan(resulting_yaml, owner_plan)

return cls(resulting_yaml)
        

```

**Comment by giovanni-guidini** [comment]
For the indirect changes tab, currently it's not displayed in the team plan. That is controlled in the frontend (see [here](https://github.com/codecov/gazebo/blob/main/src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.jsx#L62-L88))

While we could go the same route I feel that it would be better to do it on the api side and not send the data to the frontend at all.
On the front end, if we decide to leave the tab (maybe render but deactivated) it's a good place to either
1. put a "pro only" message explaining that it's a pro only feature (if user is in team plan)
2. explain how to opt into that feature if the user wants, and why it's not on by default

**Comment by giovanni-guidini** [comment]
There's been a small hiccup here due to the fact that Owners don't have a `created_at` column. They do have a `createstamp` but it was only used during login (in legacy)

Looks like legacy is gone now.
So we will be reclaiming that column and adding that createstamp when an Owner is created. This will let us pin to only new owners according to plan.
