### ISSUE TITLE
Improve the label of CI status filter

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1405]
##### Description
The label of the CI status filter is getting more confusing with failed and flaky tests design. CI only has two statuses which is passed or failed. 

![Screenshot 2024-03-12 at 5 05 17 PM](https://github.com/codecov/engineering-team/assets/152432831/140889ee-c510-4bea-8b46-c53313d1a90f)

## Possible solution
Is "build" status making sense? @rohan-at-sentry can you recommend a better label for the filter?

#### Action Checklist for Issue Creation
- [ ] Add the design project (to the right under "projects" > settings icon > select "design team")
- [ ] Share in relevant Slack channel (#discuss-codecov-product-design) for visiblity
- [ ] Add targeted launch date/delivery date as/if needed

**Comment by rohan-at-sentry** [comment]
**Step 1**

We need to figure out what `CI status` actually refers to. It seems like it's a proxy for Codecov processing state - see
https://github.com/codecov/internal-issues/issues/121 

**Step 2**

For upcoming features in UI (test analytics) - it would be helpful to have a UI element that allows you to filter commits by wether they failed CI (which is a good proxy for failed test)

Potential path forward

- [now] Rename the label to be `Codecov Processing Status` (or whatever best captures  https://github.com/codecov/internal-issues/issues/121 
-  [later] Create a new filter for `Test failures` for (test analytics) that actually filter commits / prs where there is atleast 1 failed test

**Comment by Adal3n3** [comment]
Created a fresh issue https://github.com/codecov/engineering-team/issues/1584 to reflect the fixes. Closing this one as it's duplicated.
