### ISSUE TITLE
Missing upload labels

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1475]
**Describe the bug**
Often time, the upload labels didn't load on the UI.
Example: https://app.codecov.io/gh/codecov/gazebo/commit/836f0edb681f32efb3249e29d408853b149876e2 
![Screenshot 2024-03-26 at 4 28 28 PM](https://github.com/codecov/engineering-team/assets/152432831/cd3e499b-3c8e-4eca-afaf-4a8fde7f47b5)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tnt-sentry** [comment]
@thomasrockhu-codecov to check the CLI side of the integration. Will pass off to platform if not a CLI issue.
