### ISSUE TITLE
Investigate Leveraging generator-based sync_repos backend from Gazebo (repo streaming)

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#1477]

**Comment by ajay-sentry** [comment]
**DEV NOTES:**

From the gazebo side, the main issue looks to be that the user isn't receiving any feedback until syncing repos is complete. 
How this works currently is we:
- Click the button to sync repos
- Tell worker that we want to sync repos for a particular owner
- worker makes a call to GH / other provider and fetches the user's repos
- worker upserts into our DB any new repos or changes to existing repos, yada yada
- While the above is happening the user gets a loading spinner saying "syncing"
- Gazebo continues polling every 2 seconds checking to see if the syncing is "successful" or errors
- Upon a successful signal, we finally refetch the new set of repos and show to the user.
  - This happens after worker finishes upserting ALL repos for the user
  - For large owners / orgs this process could take a while, and it's not super intuitive that anything is happening
