### ISSUE TITLE
Improve Failed tests PR comment display by grouping by suite and removing tables

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1524]
## Problem to solve
We found that using a two-column table to display all the failed tests resulted in unreadable failure messages. A suggested solution is to remove the table and instead group the tests by test suite.

Example: https://github.com/dcramer/peated/pull/153

![Screenshot_20240408-105635](https://github.com/codecov/engineering-team/assets/152432831/d753bc59-1f14-4e95-9316-ac43e84d30be)

## Possible solution
Propose a new design as suggested above.

**Comment by Adal3n3** [comment]
@rohan-at-sentry @joseph-sentry 
Design update: Figma [link](https://www.figma.com/file/HsTf9J1aYx0ur9kwH8MXrm/GH-1341?type=design&node-id=61-3802&mode=design&t=W7BuFCPQFuUl3QWO-4)

- Removed table
- Group by test suite. Display it on a h2
- Added "View git blame" link
- Added 2 drop-downs: failed and flaky tests
- Test name: From @rohan-at-sentry  the pattern is "path to test" :: "test name" at least in this case. We may need patterns for pytest vitest jest to start with https://github.com/codecov/engineering-team/issues/1551
- Env: From @joseph-sentry env is just the flag(s) they label the upload with.
   - show Env on the flaky tests. 
   - showing nothing if customers don't send us flags 
   - https://github.com/codecov/engineering-team/issues/1550
- Markdown: [Link](https://github.com/codecov/engineering-team/issues/299#issuecomment-2048102549)

![Screenshot 2024-04-10 at 11 10 54 AM](https://github.com/codecov/engineering-team/assets/152432831/ad346cde-39ba-4438-9d37-68dedc61ef3d)

**Comment by rohan-at-sentry** [comment]
should be able to parse out test name - https://github.com/codecov/engineering-team/issues/1551

**Comment by joseph-sentry** [comment]
Fixed by: https://github.com/codecov/worker/pull/504
