### ISSUE TITLE
Add link to docs to turn on Project coverage on the welcome PR comment for new orgs

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1683]
**Is your feature request related to a problem? Please describe.**
Now that https://github.com/codecov/engineering-team/issues/1078 is live, we should anticipate that new users may not realize they can turn on project coverage unless they visit docs.

**Describe the solution you'd like**

- Have a CTA on the new PR comment to link to docs. Use the following text below the last line in the screenshot

ℹ️ You can also turn on [project coverage checks](https://docs.codecov.com/docs/common-recipe-list#set-project-coverage-checks-on-a-pull-request) and [project coverage reporting on Pull Request comment](https://docs.codecov.com/docs/common-recipe-list#show-project-coverage-changes-on-the-pull-request-comment)

<img width="816" alt="Screenshot 2024-04-30 at 12 19 48 PM" src="https://github.com/codecov/engineering-team/assets/87861036/8f91c2ef-9ed3-401a-80db-3f50497fc3a0">

- Only display this for
    - Public repos
    - Private repos of new orgs (as of 30th April 2024) that belong to any plan except `team` plan

**Comment by nora-shap** [comment]
@rohan-at-sentry double checking the display logic:
- Only for the `Welcome Message` (if this is the first PR that has coverage)
- if repo is public: always yes
- if repo is private: yes IF they are not on a team plan AND owner.createstamp is after 5/1/2024 00:00:00UTC

**Comment by rohan-at-sentry** [comment]
@nora-codecov 

Slight tweak (not sure if that changes the logic). The expectation is

- If repo is public : Only for the `welcome message` (if this is the first PR that has coverage) and `owner.createstamp` is after 5/1/2024 00:00:00UTC
- If repo is private and if they are not on a team plan : Only for the `welcome message` (if this is the first PR that has coverage) and `owner.createstamp` is after 5/1/2024 00:00:00UTC

**Comment by nora-shap** [comment]
oops I missed the createstamp check on public repos! revising...
