### ISSUE TITLE
[Accounts] Decide on new data model structure

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1711]
Work with the wider team to determine the proper structure for this functionality. The end goal is a meta object that links users/orgs to allow us configure options for multiple groups of users (e.g. github orgs). 

Proposed structure

```mermaid
erDiagram
    ACCOUNT }|..|{ USERS : "has and belongs to many"
    ACCOUNT ||..o{ ACCOUNT_SETTINGS: "has zero or many"
    ACCOUNT ||..|{ OWNERS_ORGS : "has one or many"
    USERS ||..|{ OWNERS : "has one or many"
    OWNERS }|..|{ OWNERS_ORGS : "has and belongs to many"
    USERS ||..o| SENTRY_USER : "has zero or one"
    USERS ||..o| OKTA_USER : "has zero or one"

```

Note that I added account_settings here. That is not a requirement for this KR but will be needed for OKTA. We can either add that here or on that KR.

Also note that `owners` and `owners_orgs` are the same table. I broke them out for clarity here .... just like they should be in the db but alas.

Everything but `account` and `account_settings` already exists in the above diagram.

Account - meta object representing a collection of users and gh/bb/gl organizations
Owner - gh/bb/gl user
User - meta object representing a user of the system
Owner_org - gh/bb/gl organization
Sentry_user - Sentry user information for a given Codecov user
Okta_user - Okta user information for a given Codecov user

**Comment by nora-shap** [comment]
summary doc https://www.notion.so/sentry/Codecov-Billing-67bc332086cb45babdc0da513bdfb566?pvs=4
