### ISSUE TITLE
Add ability to pin a GH app to a given commit for notifications

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1737]
When a comment/check is made by a specific GH app on a commit, cache which app was used. Use this app on subsequent requests if possible.

**Comment by giovanni-guidini** [comment]
The current idea is to cache the app in Redis. This has some benefits as it's fast to access and shared among the different worker nodes.

The thing is that we problem should treat Redis as a permanent store and give the keys some expiry date. This could be very long, but that might not be ideal. Maybe 15 days is enough time for most cases. This believes in a certain amount of "time locality" in commit notifications that is quite reasonable.

However there are many commits in a Codecov instance over 15 days. We need to make sure that we can hold this much extra data in the instance.

As a "permanent" solution to go with the Redis one we can possibly extend the `CommitNotification` object ([see here](https://github.com/codecov/worker/blob/2637eef9b4c766ef5703df911b3c38f23441bf2c/database/models/core.py#L502))
We can save the GitHub app used for the notification and pull that back up if the redis cache is empty.

There's yet another alternative that is to query github directly. Their API returns the app used to send a _check_ (not status) OR comment.
