### ISSUE TITLE
[OKTA] Add user login check to account -> account settings for OKTA

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1745]
On user login follow the flow outlined below:

```mermaid
flowchart LR
    A[User Login Request]
    A --> B{Check for Account Settings}
    B -->|No settings| C[Normal Login Flow]
    B -->|Settings present without authentication modifications| C
    B -->|Settings present with authentication modifications| D[Modified Login Flow]
```

Modified login flow will be the OKTA login flow we already have created. Design this so that we can use other flows e.g. Sentry or any other 3rd party auth provider we add.

**Comment by michelletran-sentry** [comment]
Ah, this ticket might not make sense anymore. The currently workflow will assume that a user is already signed into GitHub, and Okta is another layer of authentication _on top_ of the user's login authentication. I don't think the workflow for signing in the user straight from Okta will be in scope for now. 

In a diagram:
```mermaid
flowchart LR
    A[User Login to Code Provider]
    A --> B{Attempts to view Org<br/> that requires extra Okta<br/> configurations}
    B -->|No settings| C[Show Organization's private repos]
    B -->|Settings present and<br/> already logged into<br/> Okta for that Account| C
    B -->|Settings present and<br/> not already logged into<br/> Okta for that Account| D[Show Okta Login Flow<br/> for that Account]
```
