### ISSUE TITLE
Update the old inconsistent TextInput field on the billing page

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1759]
## Problem to solve

In the billing page, we have these two form fields - email and payment method are using the old version of TextInput. 
![Screenshot 2024-05-16 at 1 16 52 PM](https://github.com/codecov/engineering-team/assets/152432831/ab4cfe5b-26d5-4d18-a478-4e803af89d3f)

## Possible solution
Swap the old TextInout fields to the one in Storybook. 
Storybook: https://5fa9228f77839a00217f8a45-skelcuitot.chromatic.com/?path=/docs/components-textinput--docs
![Screenshot 2024-05-16 at 1 17 03 PM](https://github.com/codecov/engineering-team/assets/152432831/59f24bf3-6a5d-404a-b3e6-60cb6941c824)

**Comment by Adal3n3** [comment]
We will create another inconsistent TextInput when we release the cardholder name, address, phone number section on https://github.com/codecov/engineering-team/issues/1506
![Screenshot 2024-05-16 at 1 27 57 PM](https://github.com/codecov/engineering-team/assets/152432831/9518111c-9674-414e-abb4-37cd4b2d90c0)

@katia-sentry @ajay-sentry @aj-codecov This ask is focusing on the style only.

**Comment by Adal3n3** [comment]
@katia-sentry Can you assign this?

**Comment by ajay-sentry** [comment]
From 5/23 sync, we want to update this component to the one line CardElement from stripe. This should be a plug and play with the existing backend logic; just need to update some code here: https://github.com/codecov/gazebo/blob/eefdefe3f5d26e8209760674e5ce3d9863e6eb4b/src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/CreditCardForm.jsx#L43-L54

Additionally, turn off Link and Zip Code.

**Comment by ajay-sentry** [comment]
Make it look like this: https://5fa9228f77839a00217f8a45-skelcuitot.chromatic.com/?path=/docs/components-textinput--docs
