### ISSUE TITLE
Remove the "Subscription Update Failed" banner when there has no actual error

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1795]
##### Description
If a customer goes to Stripe checkout page and then click on return, we trigger this error banner and tell them update failed which is misleading because nothing has failed.
<img width="526" alt="Screenshot 2024-05-21 at 3 30 38 PM" src="https://github.com/codecov/engineering-team/assets/152432831/c48ec880-3de3-403f-bbee-41c9bc925598">

## Solution
Remove the error banner.

**Comment by Adal3n3** [comment]
@ajay-sentry Can we detect an actual failed payment? and indicate the failed payment in an error banner here?

**Comment by ajay-sentry** [comment]
@Adal3n3 We should be able to use the "delinquency" status on the owner model for now and if it exists for a user, we can show the payment banner
