### ISSUE TITLE
Refresh the Cancel Account page

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1796]
##### Description
The design on this page is inconsistent with our current design.
<img width="523" alt="Screenshot 2024-05-21 at 3 45 36 PM" src="https://github.com/codecov/engineering-team/assets/152432831/a320ba77-601c-4362-a03b-1c4885a0f603">

#### Action Checklist for Issue Creation
- [ ] Add the design project (to the right under "projects" > settings icon > select "design team")
- [ ] Share in relevant Slack channel (#discuss-codecov-product-design) for visiblity
- [ ] Add targeted launch date/delivery date as/if needed

**Comment by Adal3n3** [comment]
@ajay-sentry Following up on can the service allows us to post Codecov logo instead of a sad emoji?

**Comment by Adal3n3** [comment]
I think this issue has been completed, let me double check w @ajay-sentry

**Comment by ajay-sentry** [comment]
Yep this is done!
