### ISSUE TITLE
[Accounts] Provision accounts for net new users on sign up

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1806]
Depends on #1740 

When a user signs up for the first time, link them and any orgs that they own to a new account.

If that org already exists on an existing account, link them to the existing account.

Consider edge cases around org ownership.

**Comment by michelletran-sentry** [comment]
This is only applicable to Github Sales led Enterprise accounts. Those will be created manually through Django Admin. There is no account creation on sign up for now. Accounts will be created lazily for Okta. 

Closing this ticket.
