### ISSUE TITLE
[Accounts] Backfill existing orgs with accounts

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1807]
For existing orgs, create an account.

 Add the `plan_activated_users` for the org as users to the account. Note that this column is actually ownerid.

**Comment by michelletran-sentry** [comment]
We're not going to migrate all the existing orgs for now. We have already migrated the enterprise orgs from the spreadsheet in https://github.com/codecov/engineering-team/issues/1808 We can consider backfilling the rest of the orgs in the future.
