### ISSUE TITLE
[Billing] Missing default payment method on the invoice

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1810]
##### Description
- The invoice is supposed to show the user's payment method they used, like card number and address.
- The Codecov logo img link is broken. 

![Screenshot 2024-05-22 at 5 22 06 PM](https://github.com/codecov/engineering-team/assets/152432831/a091e73a-0392-4854-97a4-da7673ddf4e8)

#### Action Checklist for Issue Creation
- [ ] Add the design project (to the right under "projects" > settings icon > select "design team")
- [ ] Share in relevant Slack channel (#discuss-codecov-product-design) for visiblity
- [ ] Add targeted launch date/delivery date as/if needed

**Comment by ajay-sentry** [comment]
Closing out for now since we've shipped an MVP fix. Can reopen or create a new issue if we want different styling
