### ISSUE TITLE
Failed Tests API (publicly accessible)

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1834]
**Is your feature request related to a problem? Please describe.**
As a developer, I care about pushing changes to production _**quickly.**_ 

As a dev-ops engineer, I care about ensuring my pipeline runs fast, and only necessary tests.

When a PR / commit has failing tests, the first thing I want to do as a developer is 

- Re-run tests to establish / rule out flakes
- fix tests one at a time to ensure changes can be merged.

In both cases, as a developer, I'd like the ability to ensure I don't run all tests that passed so I don't have to wait too long. As a devops engineer, running only failed tests in the above scenario is a good way to find flakes and ensure my developers are productive.

**Describe the solution you'd like**

We could return a list of failed tests for every commit via our public API. This allows for automation to be built by the customer / user to only run those tests on a retry (with a custom test runner plugin, or other techniques)

**Describe alternatives you've considered**
A future step could be to have codecov's own test runner plugin that queries this API under the hood, and runs those tests automatically. We'd need to have more concrete data about test ordering (and be confident that the order of these selected tests are appropriate that they can be run in isolation). Because we don't have this, doing just the API is a safer first attempt.

**Comment by bukzor** [comment]
This is my "straw man" design that would be Good Enough to make me happy. I'll accept anything equivalent, to be clear :)

```console
$ curl "api.codecov.com/test-results/$SHA?failed=true&fields=test,fail,pass,min-run-time"
{
  fields=["test", "fail", "pass", "min-run-time"]
  data=[
    ["foo.py::test1", 1, 1, 3.205123000],
    ...
  ]
}
```

I'm not sure whether min, max or average runtime is what I'd want here... The aim is to be able to tell the user which _single_ test they should focus on next. An expert user would pick the "fastest" test.

**Comment by RulaKhaled** [comment]
you can find investigation doc [here](https://www.notion.so/sentry/Endpoint-Design-for-Retrieving-Test-Results-f71f7ed254fe4cdeb08d6933b7c8e2a3) i'll create a ticket for implementation

**Comment by RulaKhaled** [comment]
Implementation ticket found here https://github.com/codecov/engineering-team/issues/1975
