### ISSUE TITLE
Incorrect uploads count

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1880]
Slack thread: https://sentry.slack.com/archives/C04MTDH3ZQA/p1717714477894219

The number of reports targeting this line that bubble - the number might not be alway correct.

![Screenshot 2024-06-07 at 2 16 45 PM](https://github.com/codecov/engineering-team/assets/152432831/58fc85b6-4eeb-4091-b1ed-34d2fdb9e8e1)

**Comment by ajay-sentry** [comment]
Think I was also confused looking at this page, this could be fixed with Rula's update here: https://github.com/codecov/gazebo/pull/3157

Going to assign this one to her so she gets credit and close out
