### ISSUE TITLE
[Gazebo] Add Tax Info to Plan Page

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#1973]
Confirm designs with Adalene

tax_ids should already be coming back from account-details rest endpoint, so just need to show them on the page

**Comment by Adal3n3** [comment]
View Tax ids on the plan page - Figma: [link](https://www.figma.com/design/zO6WE1lMvucxW2HHewFlbQ/GH-1506?node-id=2-298&t=Y3wwVUQ2Qk0Q9NNL-4)

**Comment by ajay-sentry** [comment]
As part of this ticket, should also update the invoices "See all Invoice" button to "View!" as shown in the figma link above
