### ISSUE TITLE
[Gazebo] Add Tax Info to Individual Invoice Page

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#1974]
Confirm designs with Adalene

Will also need to update the queries in useInvoice and useInvoices hook to fetch the taxId information

Related API review: https://github.com/codecov/codecov-api/pull/627 with the GQL invoice model updates

**Comment by Adal3n3** [comment]
@ajay-sentry You can find the information here on Figma: [link](https://www.figma.com/design/zO6WE1lMvucxW2HHewFlbQ/GH-1506?node-id=163-189&t=Y3wwVUQ2Qk0Q9NNL-4)
