### ISSUE TITLE
UI to support multiple orgs

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#2083]
In Q2 we've enabled support for a GH enterprise org that has child orgs under it when billing in Codecov. (ref: https://github.com/codecov/engineering-team/issues/1533) 

**Problems to Solve:**
- No ways to see or check if the orgs linked to the plan correctly.
- If admin wants to check the available and activated seats, they have to check individual orgs. If they have >10 orgs...

**Solution:** 
- Customers need an Admin-view that has access to the new accounts page in the UI.
- Only Admins will have the access to the new account page allowing them to view the list of organizations linked to the account/plan.
- Admins will need to know the number of seats for each org so they can contact support to reallocate seats from one org to another. 
- They will also need to know the total number of orgs linked to the plan.
- Admins won’t be able to remove or add organizations. They will need to contact support for these actions.
- This design applies to Enterprise Cloud plan customers.

Notion: https://www.notion.so/sentry/Support-multiple-linked-orgs-bb12636b63654fe99a45017d66cddcff
Designs: https://www.figma.com/design/Tytz3vo8mjlyAL8qSiXw3S/GH-1533?node-id=2001-12&t=PYhWeCsDscgeWlzn-0

**Comment by Adal3n3** [comment]
The lates dev-ready design is [here](https://www.figma.com/design/Tytz3vo8mjlyAL8qSiXw3S/GH-1533?node-id=1-2)
The previous related issue. https://github.com/codecov/engineering-team/issues/1533
