### ISSUE TITLE
Per commit billing for Codecov

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#2116]
Per commit billing for Codecov (What are the plans, tiers, unit prices, etc.) - new billing page?

**Comment by ajay-sentry** [comment]
Findings can be read through here:
https://docs.google.com/document/d/1hz4Jl3Y5t7UBN8sfCo7oL4EPU_bbCiB00ZG1Vx25FKI/edit

Long story short, we are deprioritizing this for now in favor of other initiatives.

CC: @aj-codecov
