### ISSUE TITLE
PR comment: XML File not found

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2149]
![Image](https://github.com/user-attachments/assets/d46c9816-83bc-4bb3-84a1-054c26141cf9)

![Image](https://github.com/user-attachments/assets/71640732-9394-44bd-a1f6-d63f9bd8d884)

**Comment by Adal3n3** [comment]
Currently, we can't detect if it's a file not found or unusable file.

**Comment by rohan-at-sentry** [comment]
Is there any errors we catch on the CLI. If so then

1. Generally we can surface this into the UI within the tests tab.
2. I imagine file not found or unusable file issues to be a problem primarily during setup (as we don't typically find people changing the format after it has been uploaded once)

**Comment by rohan-at-sentry** [comment]
Will be fixed as part of https://github.com/codecov/engineering-team/issues/2848
