### ISSUE TITLE
[OKTA] Document Okta setup process

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2159]
1. Document the setup process within Okta
2. Document the setup process with Codecov

These will serve as the rough draft for user facing docs of this feature.

**Comment by michelletran-sentry** [comment]
Instructions: 
https://www.notion.so/sentry/Setting-up-Codecov-with-Okta-9ecbe7b2ad924613841a7b9d964ba2e7?pvs=4
