### ISSUE TITLE
Calculate, store, and update flake rate for each Flake we process

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2162]

**Comment by Adal3n3** [comment]
@joseph-sentry @rohan-at-sentry to confirm

**Comment by Adal3n3** [comment]
@joseph-sentry @rohan-at-sentry wondering if we have a decision on calculate flake rate only on the main branch or across all branches?



![Image](https://github.com/user-attachments/assets/6d115b37-09cc-41eb-85de-16978a207eda)

**Comment by rohan-at-sentry** [comment]
We're only showing flake rate on main (which is what we built in Q2).
