### ISSUE TITLE
Usability improvements of the PR design with more collapse, ordering, limit to 3 tests for each section

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2179]
This issue focus on the new structure/format of the contents. 

https://github.com/codecov/engineering-team/issues/299#issuecomment-2234799978

![Image](https://github.com/user-attachments/assets/9d6539c0-3f94-4a26-8dbc-ddd9bd68fb3e)

**Comment by tnt-sentry** [comment]
We are going to omit the rerun CI button at this time. The cost to implement is high. It would only (barely) work for github actions. Also the verbiage "to get rid of flaky tests" is a bit misleading.
