### ISSUE TITLE
Improve the copy and paste-able test name + file path output in the UI

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2181]
1. Use `Mono font` on the test name column.

2. Add color-set on test name output. (Apply these code-style https://github.com/codecov/gazebo/blob/main/src/shared/utils/prisimTheme.css)
- If we add colors for all languages, it is challenging because we will need to understand the variables from different languages. (not do this for now)
- For now we color just the file name (brown) and the "/" (blue)

3. The test name should be include **the path** so for JS developer they can find their test by copy and paste the path into their terminal
This is a JS example: (from Ajay) The first line is the path, the rest is the name.
![Image](https://github.com/user-attachments/assets/8a29d601-5e98-4f6b-b4a0-d2508e3e617d)

This is the design-mock where we want to tweak:

![Image](https://github.com/user-attachments/assets/fc380b99-8b35-4147-a918-1df420fa8edc)

We are not doing individual style based on the languages because it's XXL work. We will collect more feedback for improvement.

Consider making  test-name column resize-able.
https://tanstack.com/table/v8/docs/guide/column-sizing

**Comment by Adal3n3** [comment]
@joseph-sentry we need `the path` for JS for the test-name column pls

**Comment by ajay-sentry** [comment]
@joseph-sentry has a PR up for converting the "." to "/" which will get us halfway there. Will need to think through how we want to do the color thing
