### ISSUE TITLE
Technical planning for Restructure Graphql API

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#2182]
Details about this task can be found here in the notion doc https://www.notion.so/sentry/Restructure-GQL-API-to-better-support-a-multi-product-product-46f7c984aeff4aec94c61f00926ae377
**Tasks:**
- Collaborate to ensure technical feasibility and align with user experience goals.
- Documentation and Task Breakdown:
  - Document project initiatives and plans in Notion, 
  - Create actionable GitHub issues in https://github.com/codecov/engineering-team/issues/2118
- List and include all project team members in relevant discussions and updates.
- Define clear deadlines and milestones for the project and communicate progress.

**Outcomes:**
Develop a clear implementation plan for this feature, with technical and design considerations, broken down into actionable development tickets.

**Reference:**
Guide for leading a project: https://www.notion.so/sentry/Project-Guideline-for-Engineers-37b967598a834e9ebc5bde2608d9c2f7

**Comment by suejung-sentry** [comment]
Plan is here: https://www.notion.so/sentry/Project-Plan-Restructure-GraphQL-9b47b646b797451090c733be880615e7?pvs=4
Tickets are here: https://github.com/codecov/engineering-team/issues/2118

Any spillover follow-up pre-work (e.g., finalize schema) is here: https://github.com/codecov/engineering-team/issues/2118
