### ISSUE TITLE
GA: Private repo upsell path and roll back plan or limited feature

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2242]
In beta, (flaky detection)it's free for all plans and all public and private repos.
In GA, private repos on the developer and team plans will no longer have access to the free flaky tests. 

Questions to consider:

- What will the user experience be like?
- Will we hide the feature?
- Will users still have access to stale data?
- What does the upgrade process to a paid plan look like?
- What are the technical work we need to plan for this work?

**Comment by rohan-at-sentry** [comment]
Covered by https://github.com/codecov/engineering-team/issues/2436
