### ISSUE TITLE
Investigate initial areas of improvement for tracing

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2261]
Review existing tracing and provide documented recommendations for where improvements should be made. The goal is to make some early wins and also divide the work amongst the team where applicable.

Provide a notion doc or create sub issues from the parent issue here if desired.

**Comment by Swatinem** [comment]
I would call this done, as tracing instrumentation has been massively improved since then. In particular in the `Upload`-family of tasks, things look a lot more readable than previously, and I have also helped other team members along with improving instrumentation for other tasks as well.
