### ISSUE TITLE
Review the PathFixer and provide recommendations

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2262]
At this time, no one on the team has expertise with this area of the code. 

Please dive into this code and look for improvement opportunities.

1. Does this need to be rewritten (probably in rust) as part of a larger project?
2. Are there any areas of incremental improvement that we can target prior to a rewrite?

Work with @matt-codecov / @giovanni-guidini as needed here.

Incremental improvements we can slot into upcoming sprints. The information you provide on a potential rewrite will serve as the basis for that project in an upcoming quarter.

**Comment by Swatinem** [comment]
I have been looking into this a little bit.

The main conclusion is that this code is indeed very hot, especially for big customers that have huge monorepos with tons of files.
As the `Tree` is being built with the list of files included in the repo, that list can often far exceed any kind of filenames / paths that show up as part of the coverage reports themselves.

For some slow traces / profiles, time spent in building the tree can far exceed the time needed to download the reports as well as processing the report.

![Image](https://github.com/user-attachments/assets/9adb16ad-3948-46ec-84db-5c16a1da6102)

The tree structure and the way it is being constructed seems to be quite inefficient, and I have some ideas on how to improve it even in python.

**Comment by Swatinem** [comment]
Looking at some fresh performance/profiling data, *building* the `PathFixer`/`Tree` is still hurting, especially large customers with huge monorepos with thousands of files.

Though actually applying path fixes and normalizing file paths seems to be slow in accumulation across all our processing, and it should be possible to improve that somewhat without a full rust rewrite.

So I created two followups:
- https://github.com/codecov/engineering-team/issues/2978 to improve the path normalization in Python, this should be doable with a couple of days to a week.
- https://github.com/codecov/engineering-team/issues/2979 rewriting that whole thing in Rust would be the next step, for which I estimate maybe ~2 weeks of work, maybe more as integrating it into the `worker` might take some time.
