### ISSUE TITLE
UI banner: when XML File not found

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2269]
This scenario will only happen in branch view page:

![Image](https://github.com/user-attachments/assets/847b51a3-8300-42b6-aaf6-5eace4920523)

**Comment by Adal3n3** [comment]
@joseph-sentry @ajay-sentry @RulaKhaled when a XML file not found or the user change the file name, what will they see in the UI? What can we display in the branch page?

**Comment by rohan-at-sentry** [comment]
Will be fixed as part of #2846
