### ISSUE TITLE
Add new tokens_required field for owners table

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2297]
We need a new default true field for owners (maybe accounts?) to indicate whether tokens are required at all for public repos. `tokens_required` or similar.

**Comment by nora-shap** [comment]
How about `upload_token_required_for_public_repos`?

Not going to add to Account, I want this to be set per org. Owner table still holds other permission-related fields so I feel like it fits best there. We can add to Account later if need arises.

Wouldn't the default be `False`?

I'm going to add this as a nullable boolean field with default = `False`, then backfill all existing orgs to `True`, then make it non-nullable 👍

**Comment by nora-shap** [comment]
I did end up adding this column as `default=True` because I realized this will act sort of like a feature flag, and should remain `True` for everyone until we are ready for it to go live.

I'll add a task to this epic to flip the `default` to `False`
