### ISSUE TITLE
PR comment: Communicate why a test results file couldn't be parsed

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2376]
**Is your feature request related to a problem? Please describe.**
We're noticing customers uploading `junit xml` files without a `duration` field. We currently do not support that. While we work on supporting that, it might be worthwhile to surface the error onto the PR comment.

**Describe the solution you'd like**
We already do this to a certain degree today (![Image](https://github.com/user-attachments/assets/78a68163-2dda-44ca-8955-abab7e93614a)

We can add to this. Maybe we can pull from the [Sentry Issue Summary](https://codecov.sentry.io/issues/5156905842/?project=4165036&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+TestResultsProcessor&referrer=issue-stream&statsPeriod=2d&stream_index=6).

**Comment by Adal3n3** [comment]
ToDO for Adalene: I will provide a PR comment and UI banner for the unusable file, link to the doc for the right format. Something like: this report is incorrect format link to the doc. (https://docs.codecov.com/docs/test-result-ingestion-beta#troubleshooting)

**Comment by rohan-at-sentry** [comment]
Will be fixed as part of #2848
