### ISSUE TITLE
The mode switches based on user's default system

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2403]
Add prefers-color-scheme media query in CSS

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme 

We can auto switch to dark / light mode to user based on their default system setting.

**Comment by Adal3n3** [comment]
@katia-sentry Can we add a code snippet for auto switch so the user doesn't even have to click on the icon.

**Comment by Adal3n3** [comment]
We can do this after the release for faster deliver

**Comment by ajay-sentry** [comment]
After discussing with @Adal3n3, for this ticket we will move forward with the implementation where dark mode is set depending on the user's preferred system theme until they click the button for the first time; after which it'll respect whatever the button's theme is currently set to.
