### ISSUE TITLE
[Gazebo] Create CI run efficiency section

### ISSUE THREAD

**Issue by RulaKhaled** [codecov/engineering-team#2415]
Design: https://www.figma.com/design/TcppABudxnslgEmaXm0B9O/GH-2028?node-id=2001-855&t=1c8whZB94GIederY-0

**Comment by rohan-at-sentry** [comment]
@joseph-sentry raised a valid point around needing to decide what frame of comparison we want to use. Options being 

- Date Range. Shown in red This means 
```
Show me how many flakes i have active TODAY that were active 30 days ago, compare with how many were active 30 days ago and were active for a 30 day period
```
- Point in time. Shown in green This means
```
Show me how many flakes that were active anytime in the last 30  days, compare with how many were active in the previous 30 day period.
````

This is best described in the image below



![Image](https://github.com/user-attachments/assets/426d4c40-d265-4c2b-925c-30dcaf020b74)

As we can see, the `date range` option accounts for flakes that have expired.

**Comment by rohan-at-sentry** [comment]
Moving forward w `Date Range`
