### ISSUE TITLE
{GA Launch Prep} Ensure TA honors plan details

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2436]
- If you have the developer (free) plan then you should get access to TA on public repos and on private repos for a single activated user up to 250 uploads (coverage only, unlimited TA reports). 
    - Only failed test UI and PR comment for private repos
    - No flaky test UI or PR comment (on private repos) 
    - On public repos you get flaky tests on comment + UI
- If you have the team plan then you should get access to TA on public repos and on private repos for a all activated users up to ten up to 2500 uploads (coverage only, unlimited TA reports).
   
    -   Only failed test UI and PR comment for private repos
    - No flaky test UI or PR comment (on private repos) 
    - On public repos you get flaky tests on comment + UI
    
- If you have the pro, enterprise, or a dedicated enterprise cloud plan then you should get access to unlimited TA for all activated users.
    - Full feature access across private and public repos

**Comment by rohan-at-sentry** [comment]
@trent-codecov @katia-sentry @RulaKhaled @ajay-sentry @joseph-sentry this needs to be in place before GA. I'm gonna add to next sprint - lmk if there are objections

**Comment by ajay-sentry** [comment]
Apps / Gazebo side of this work is complete

**Comment by ajay-sentry** [comment]
Unassigning myself and @RulaKhaled to get this off our board

@joseph-sentry or @rohan-at-sentry will leave it to y'all to close out!

**Comment by joseph-sentry** [comment]
done
