### ISSUE TITLE
Fix Test table ids

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#2505]
When we made the Test table, we thought we needed to have the primary id be computable by combining the name, repoid, flags, and testsuite name, so right now it's a string which is a SHA256 hash of the 4 aforementioned fields of the Test model. in hindsight this was a mistake so we should go back and fix this and make a Test table that uses a sequential integer for its primary key.

The issue with using a hash as the primary id is that it takes up more space, and sequential writes to the primary index of the table become random instead which is not something we want.

**Comment by tnt-sentry** [comment]
@joseph-sentry while I agree in spirit that this is maybe something to do, are we looking to do this now (in this ticket) or do we want to tackle this as part of the wider TA perf OKR?

**Comment by joseph-sentry** [comment]
we should include this in the solution of the TA perf OKR

**Comment by tnt-sentry** [comment]
Closing this in favor of a new issue in that KR once we make issues from the new desired state investigation.
