### ISSUE TITLE
More permissive pattern matching for JUnit XML files

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2520]
**Is your feature request related to a problem? Please describe.**
Currently Test Analytics depends on finding test results in a JUnit XML format. The logic to scan and upload is rather simplistic - we look for `*junit.xml`

While this generally works well for most customers, sometimes certain test framework/plugin combo generates a JUnit test result file that is named differently - which fails the pattern match we have implemented - causing uploads to not be sent to Codecov.

**Describe the solution you'd like**
Expand the pattern matching to be more inclusive.

- Potentially `*junit*.xml`
- Potentially `*TEST*.xml`

**Comment by joseph-sentry** [comment]
Fixed by: https://github.com/codecov/codecov-cli/pull/503 and https://github.com/codecov/codecov-cli/pull/550
