### ISSUE TITLE
Investigate slowness of ComputeComparison Task

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#2531]
Related Traces:
https://codecov.sentry.io/performance/trace/b1598eef48034ef8a0ad1618be91133a
https://codecov.sentry.io/performance/trace/91d4a713ba1147fdb81e86946ed49402

The function call here: https://github.com/codecov/worker/blob/c1fddb7eb428148a6731b042acf0c8ba738be445/tasks/compute_comparison.py#L58-L60 looks to take a longer chunk of time in some cases than we expect

There might be some low hanging fruit within the [comparisonProxy class](https://github.com/codecov/worker/blob/c1fddb7eb428148a6731b042acf0c8ba738be445/tasks/compute_comparison.py#L307-L319) itself that can be cleaned up / deduped / etc? Not too sure, but also haven't dug too deep either

**Comment by tnt-sentry** [comment]
@Swatinem please take a look at this next sprint and provide recommendations for improvements

**Comment by Swatinem** [comment]
This is an interesting one.

This task does the following operations:

- Fetch *two* `Report` objects from storage, which is its own ticket: https://github.com/codecov/engineering-team/issues/2530
- It does some calls to GitHub to fetch a patch / commits, which in part is covered by https://github.com/codecov/engineering-team/issues/2356 as it *always* involves an un-cached token request.
- Some tasks, though not all, resolve the `commit_yaml`. I’m unsure why those are not cached, but it should be possible to do so.
- Two calls to `LazyRustReport.get_report` seem to be unreasonably slow, in particular as the name suggests Rust is involved, which shouldn’t be that slow :-D This might need a deeper investigation.
- It is then storing the comparison results in GCS, which I believe should be improved by https://github.com/codecov/engineering-team/issues/2553
- And last but not least, I believe the main culprit here is an unreasonably slow `UPDATE` query:

![Image](https://github.com/user-attachments/assets/11041e0b-be06-4938-8268-42b2976c4968)

The query itself seems to be executed fairly infrequently, but it is incredibly slow: https://codecov.sentry.io/insights/database/spans/span/a02e3cca4867e02e/?project=4165036&statsPeriod=7d
Its average duration is `636ms`, with outliers well in the multiple seconds.

As the screenshot above shows, there is also multiple requests being performance (possibly for the same row).
I think this is an implementation detail of `SQLchemy`, which seems to always re-SELECT records that were previously mutated.

I think the primary thing to do here is figure out why this particular query is so slow. Maybe it is contending some database locks, or some other reason, I can’t say for sure yet.

**Comment by tnt-sentry** [comment]
The tickets above will help with the performance. We can revisit this general ticket if the performance is still poor after implementation.
