### ISSUE TITLE
Codecov Uploads only require 1 network request for basic usage

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2535]
The current upload process with the CLI requires a call to create commit, create report and then do upload. Each of these endpoints only take the commit sha as the input. As such there is no reason for these to be separate calls in the basic scenario. Users can still call the individual endpoints for more advanced scenarios.

Goals:
* Create single endpoint in API
* Update CLI to use this endpoint with the wrapper command
* Update GHA to use wrapper command by default

**Comment by ghost** [comment]
Closing this as completed. Repositories using `codecov-action@v5` should be using this new `upload-coverage` endpoint.
