### ISSUE TITLE
[CI-Wrappers] Migrate other CI wrappers to use `upload-process`

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2541]
* Circleci orb
* Bitrise step
* others?

**Comment by ghost** [comment]
CircleCI - https://github.com/codecov/codecov-circleci-orb/commit/cd4f651c0663827d9a7232c6eed1ed44932e5663
Bitrise - https://github.com/bitrise-io/bitrise-steplib/pull/4325
