### ISSUE TITLE
Detect when the JUnit format being upload is not optimal or consistent from the previous upload

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2587]
From @joseph-sentry 

detect when the JUnit format being upload is not optimal (for example not using `pytest --junit_family=legacy` and notifying the user to fix it in the comment and possibly the UI.

This might not be an error case, it's more like we notice that some stuff is missing from the JUnit XML and we know that it's usually there when the right setup is being used.

**Comment by rohan-at-sentry** [comment]
the ideal state would be to detect cases such as https://github.com/codecov/feedback/issues/543 and surface what's missing in the PR comment and UI

**Comment by rohan-at-sentry** [comment]
This should be returned from parser anyway, so nothing special needed here
