### ISSUE TITLE
Better understanding of filtered state.

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2693]
With filter

![Image](https://github.com/user-attachments/assets/6fea665e-cf70-4d9e-a79f-ec1b47fbc94e)

Without filter 

![Image](https://github.com/user-attachments/assets/3415ba10-8f6f-4a2a-b2a5-7bc29982571d)

The differences between the filtered and non-filtered state are subtle.. From what I can see it's

- Active "reset to default button"
- Prominent bold hyperlink state below 100

 WE should explore ways of making it a little more prominent, because on navigating away and coming back it isn't clear if I have a filter on or off

**Comment by Adal3n3** [comment]
On the filter mode: the title of the table will display the filter-name and count of the filtered test.
![Image](https://github.com/user-attachments/assets/6c0861c7-9f58-4af1-820f-d8eec06210b8)

**Comment by RulaKhaled** [comment]
I'll be tackling this alongside https://github.com/codecov/engineering-team/issues/2707

**Comment by RulaKhaled** [comment]
With the copy change in the tests header, I think these three together are enough to clarify that the filters are on
