### ISSUE TITLE
{investigation} How can Codecov know the latest run for a commit?

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2715]
**Background**

We want to build a debugging experience around upload errors that doesn't require a new commit to be triggered (a lot of upload error scenarios can be mitigated by simply re-running CI ; and asking a user to open a new commit for these is not the greatest UX).

Today, the Codecov UI doesn't update itself on subsequent runs on the same commit - meaning any experience we build would be stale (in the error --> re-run --> success state, you'd still see an error on the UI)

One of the challenges is that we don't really know the latest run for a commit - meaning we have no clue if reports for a given commit are coming from the same run or a different run.  

Investigate the APIs of Github Workflows, Circle CI, Bitrise and see how (for a given git commit sha) we can receive 

1. How many workflow runs were associated with that commit
2. Time-stamps of those runs

From 1 & 2 - you receive "latest run"

3. How can we return the status of uploads from this "latest run"
-ANS: from @suejung-sentry yes, we can return the "latest run" in the UI

**Comment by ajay-sentry** [comment]
@rohan-at-sentry To confirm, we're looking to see if there are ways we can subscribe to events that occur on the latest Commit of a Diff (not necessarily a Pull Request even), and if so, unpack the payloads from those events and see if there's useful information we can derive and subsequently show the user in real-time? And this is only for the Codecov UI / Gazebo

**Comment by rohan-at-sentry** [comment]
> And this is only for the Codecov UI / Gazebo

Correct


> subscribe to events that occur on the latest Commit of a Diff (not necessarily a Pull Request even)

Sort of.

1. This needs to be scoped to the payload returned by querying the CI provider. i.e. for a given commit, what are the {set of CI "runs"} that the CI provider performed + timestamps.

2. If we get this back reliably, then we can likely have the UI react to it . For example, we could on the commits / pulls page poll a list of "runs" for a SHA, and if we get a {set of runs}, pull data from the reports associated with the latest (from timestamp) run.

 Hope this clarifies

**Comment by ajay-sentry** [comment]
@rohan-at-sentry Could you confirm that this webhook contains the information we need? https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=requested#workflow_run

At a baseline, for each Github workflow run on a repository, there are three actions:

- Requested
- In-progress
- Completed

Under the "workflow_run" object in the event payload, there are attributes like the head/base commit sha, pull requests, etc.

**Comment by ajay-sentry** [comment]
If so, I can look to see if other CI providers have similar webhooks, and if we also have webhook infrastructure that we can build off of like I know we already do for Github

**Comment by rohan-at-sentry** [comment]
I think that's the right API yes. 

It looks like it returns commits against a given run. What we need is runs for a given commit (so you're gonna have to find a way to creatively return that / explore if that's feasible - which is the goal of this story)

**Comment by suejung-sentry** [comment]
Here is the results of my investigation on this topic: https://www.notion.so/sentry/Get-workflow-state-from-CI-provider-APIs-1518b10e4b5d80298a37e0ac0192b1b0?pvs=4
