### ISSUE TITLE
Create a prioritized list/plan for mypy type conversions in api repo

### ISSUE THREAD

**Issue by suejung-sentry** [codecov/engineering-team#2756]
Create a ticket with an ordered list of mypy type conversions in api repo that we can start chipping away at in order and add it to this epic (https://github.com/codecov/engineering-team/issues/2754)

Goal is the try to reduce the failures in the CI red X failures so we can start trusting/enforcing that step.

**Comment by JerrySentry** [comment]
See https://github.com/codecov/engineering-team/issues/2894
