### ISSUE TITLE
Include parser error messages in the PR comment

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#2799]
We currently log the parser error message to our internal logs, but we don't surface them to users, so they don't know what about their JUnit XML caused the error. If they knew, they'd have more information and possibly be able to fix it.

I want to include the parser error message in a new nested section of the PR comment.

**Comment by rohan-at-sentry** [comment]
Will be fixed as part of https://github.com/codecov/engineering-team/issues/2848
