### ISSUE TITLE
Investigate changing commit update behavior

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2824]
This query below is running MANY times and is a big contributor to lock contention on the commits table. 

[Sentry DB link](https://codecov.sentry.io/insights/database/spans/span/0ea8c24d682118d8/?project=4165036&span.description=update%20commits&statsPeriod=1h)
```
UPDATE
  commits
SET
  message=$1,
  merged=$2
WHERE
  commits.id = $3
```

It appears that the majority of the updates listed are caused by [this function.](https://github.com/codecov/worker/blob/main/services/repository.py#L220)

Action items:
1. Investigate if this function call is needed in both PreProcessUpload and UploadProcess
2. Investigate committing the update transaction right after the commit hydrate. [Sentry trace](https://codecov.sentry.io/performance/trace/16eb0bf7f972410d9232042a328063cb/?groupId=0ea8c24d682118d8&node=span-ba0a8562233338cf&node=txn-655b408d97ca488c840e1566eeae73d1&project=4165036&source=queries_module&span.description=commits&statsPeriod=30d&timestamp=1727981935&transaction=app.tasks.upload.PreProcessUpload&transactionMethod=) Depending on when we commit (my understanding is that it is at the end of the task), this update has to wait on N number of selects to find parent commits, multiple calls to GitHub etc.

[Slack context while it exists](https://sentry.slack.com/archives/C04NC9NNPEG/p1730405162944299?thread_ts=1730297209.274919&cid=C04NC9NNPEG)

**Comment by Swatinem** [comment]
I shipped 2 improvements in the past days:
- one merging two separate `UPDATE` queries into one
- the other one completely removing updates to the `Commit.notified` field which was never read

There is a clear trend visible in traces touching that table:
![Image](https://github.com/user-attachments/assets/9484042f-5508-4a67-8289-b6b99cf20670)

Though it might be a bit early to tell whether this has made any significant improvements to our database contention, I would still close this as done. We can surely revisit this at a later point.
