### ISSUE TITLE
Static Analysis MVP Discovery

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#2838]
Explore available dataset with Eli and possible MVP solution

**Comment by suejung-sentry** [comment]
Connected with Eli and Gio
* Skimmed the research [repo](https://github.com/codecov/bug-prediction-research)
* Got access to the postgres dataset and played around with it
* Got added to the weekly status meetings
* For now, no immediate tasks, but will stay plugged in

![Image](https://github.com/user-attachments/assets/3a9a6658-ffdf-4b26-b773-c49741d9295c)
