### ISSUE TITLE
Clicking the flaky test filter shows the wrong result

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2852]
Expected - show 0 
Reality - shows all tests as flaky tests

https://github.com/user-attachments/assets/e8de20cb-b768-45b2-9d1d-c83e0aa36afc

**Comment by Adal3n3** [comment]
Another bug on the **failures filter.**
In gazebo, I clicked on the **4 Failures, it shows 3 failed tests**.
![Image](https://github.com/user-attachments/assets/46d3787e-7c60-490c-b950-7c92ef392010)

**Comment by Adal3n3** [comment]
Skipped tests filter
![Image](https://github.com/user-attachments/assets/9a42ab91-b88e-44fd-b73b-578541f9e0ac)
