### ISSUE TITLE
Incorrect link for the feedback

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2865]
See this example: https://github.com/codecov/worker/pull/862#issuecomment-2462117470 

Currently the feedback link goes to all issues: https://github.com/codecov/feedback/issues

The correct link is https://github.com/codecov/feedback/issues/304

![Image](https://github.com/user-attachments/assets/2ae1f56b-46ca-4719-8a05-c509a1ff0bce)

**Comment by rohan-at-sentry** [comment]
once it GA's It likely makes more sense to direct to feedback/issues. We don't want to overcrowd #304

**Comment by rohan-at-sentry** [comment]
not doing

**Comment by rohan-at-sentry** [comment]
once it GA's It makes more sense to direct to feedback/issues. We don't want to overcrowd https://github.com/codecov/engineering-team/issues/304
