### ISSUE TITLE
No flags data in flags dropdown

### ISSUE THREAD

**Issue by suejung-sentry** [codecov/engineering-team#2870]
Not sure if this is meant to have data, but the Flags dropdown list is empty even if the Flags list is populated in the Coverage tab. Maybe this is the intended behavior if you can specify flags for each product line separately?

![Image](https://github.com/user-attachments/assets/3f411481-a310-4c5d-b277-15d0cd3f86ec)
![Image](https://github.com/user-attachments/assets/7a51d522-5c00-4198-86ef-279399bccc9a)

**Comment by ajay-sentry** [comment]
@suejung-sentry Super confusing, but apparently these are different flags 😅 

CC: @rohan-at-sentry

**Comment by rohan-at-sentry** [comment]
yep see https://docs.codecov.com/docs/test-analytics-beta#flags

**Comment by suejung-sentry** [comment]
Ah perfect - thank you!!
