### ISSUE TITLE
Mismatched total failures?

### ISSUE THREAD

**Issue by suejung-sentry** [codecov/engineering-team#2872]
The Improve Test Performance > "Failures" total representing "The number of test failures across all branches"  on the page for `main` says 3 but when I was on a different branch (`joseh/fix-deadlocks`) checking it out there were 7 failed tests. Not sure if that's a bug in the total "number of test failures across all branches" or just me looking at things wrong

![Image](https://github.com/user-attachments/assets/2369d499-ae66-4a42-a767-ce3b463f6890)
![Image](https://github.com/user-attachments/assets/a8ad3f9d-276f-4138-8f04-7dc61a70022c)

**Comment by ajay-sentry** [comment]
This should be fixed with a @joseph-sentry PR that is currently in the works (we hope)
Will revisit and keep this open in case it's not though

**Comment by rohan-at-sentry** [comment]
This was a copy issue. The data tile you see on main is the  # of failures on default branch. The copy has been updated since the time this issue was opened
