### ISSUE TITLE
[For Sentry only] Incorrect results for the historical trend filter with Total test run time

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2888]
_This happens to Sentry repo only._

Last day --> 19 d 
Last 7 day --> 17 d
Last 30 day --> 14 d

These results don't make sense. Last day is only 24 hours but it shows the total test run time is 19 days unless the team hired more developers running these tests on the last day.
https://app.codecov.io/github/getsentry/sentry/tests/master?historicalTrend=INTERVAL_30_DAY&parameter=FAILED_TESTS 
![Image](https://github.com/user-attachments/assets/7dd38eee-681d-41fa-ba04-7bd066f12eea)
![Image](https://github.com/user-attachments/assets/0eaf9e9e-ddf3-45d7-88ed-687510b29973)
![Image](https://github.com/user-attachments/assets/30682e49-aa20-461a-9aac-b7038bbc74a5)

**Comment by rohan-at-sentry** [comment]
This was diagnosed to be due to the sentry repo uploading about 6k times for a single commit
