### ISSUE TITLE
Update UI copy for Cumulative Failure

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2942]
Change the description from "The number of test failures across all branches" to "The number of test failures on main branch"
![Image](https://github.com/user-attachments/assets/0584a48d-b3b3-457b-a239-199be6b74308)

change the copy back when we ship "across all branches" in q4 https://github.com/codecov/engineering-team/issues/2542

**Comment by rohan-at-sentry** [comment]
The copy shouldn't change back once we ship in 2542. 

The copy on main should be for as described in this ticket. The copy should only change once we select "all branches"
