### ISSUE TITLE
PR comment messaging

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2987]
For PR comment

- Scope messaging to orgs using Impact Analysis (bonus if we can scope to repos of orgs)
- Use this message

```
Impact Analysis from Codecov is deprecated and will be sunset on Jan 31 2025. See more <https://docs.codecov.com/docs/impact-analysis>
```

**Comment by michelletran-sentry** [comment]
Any preference on where to put the message? I'm currently appending it to the end of the comment like:

[:umbrella: View full report in Codecov by Sentry](https://app.codecov.io/gh/codecov/worker/pull/949?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov).
:warning: Impact Analysis from Codecov is deprecated and will be sunset on Jan 31 2025. [See more](https://docs.codecov.com/docs/impact-analysis)


cc/ @rohan-at-sentry

**Comment by michelletran-sentry** [comment]
PR: https://github.com/codecov/worker/pull/951

**Comment by michelletran-sentry** [comment]
Repos that I'm going to turn this on for: 
* 19207156 (recent profile commits)
* 11827021
* 15252118
* 14288854

These look to the be only repos who seems to be active since May, so will set messaging for them.

**Comment by michelletran-sentry** [comment]
I've set the feature flags for the repos above. Marking this as done.
