### ISSUE TITLE
[Client] Investigate updating seat allocation and messaging

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#462]
Investigate the requirements to update seat allocation and messaging according to the Solution Ideation plan found at https://github.com/codecov/engineering-team/issues/324. Collaborate with the design team to establish a technical direction for this task.

Note: An investigation for the API side has already been conducted, as listed in the tasks https://github.com/codecov/engineering-team/issues/324. However, it has been some time since this occurred. As part of this task, please review and improve the API work as necessary.

Acceptance Criteria:

- Comment on this issue with a write-up of the investigation results.
- Create issues for the necessary work in: https://github.com/codecov/engineering-team/issues/324.

**Comment by RulaKhaled** [comment]
First pass for scenarios, this will be drafted in a notion doc once it's polished:

**Org Repos** 

1.  User is not activated, on free plans, no seats left.
     Sol. Upgrade button for private repos in org table.

> _Notes_: 
> _We need to know if there are any available seats left in the plan_
> _If alternative plan, we need no seats number_.


**API Fields needed**:
- Either 
      - Seats count (Int) 
      - Is current user activated (Bool) ✅
      - Activated users count (Int)
      - Plan value (String) ✅
- OR (less calculations in the frontend, better)
      - Seats count (Int) 
      - hasSeatsLeft (Bool) => activated users < seats
      - Is current user activated (Bool) ✅
      - Plan value (String) ✅

**Questions**:
   - Plan users count === seats 
   - New field of hasSeatsLeft => activated users < seats

 
2. What if plan is paid? What’s the overview in org repos? 


**Repos > Repo** 

1. User is not activated, on paid plans, no seats left.
	Sol. Seat limit reach screen.
	
API Fields needed:
  	 (less calculations in the frontend, better)
    - hasSeatsLeft (Bool) => activated users < seats
    - Is current user activated (Bool) ✅
    - Plan value (String) ✅

	
2. User is not activated, on paid plans, some seats left.
	Sol. Activate toggle on spot 

**API Fields needed:**
    (less calculations in the frontend, better)
    - hasSeatsLeft (Bool)  => activated users < seats
    - Is current user activated (Bool) ✅
    - Plan value (String) ✅
    - New mutation for user activation (user activate_user func in owner)
		

**Questions**:
	- Can we redirect to manage members? single point of failure. 

3. User is not activated, on free plans, no seats left.
	Sol. Coverage alert, surface overview on plan

> _Note: Leverage current plan page for free users_.

**Questions**:
  - Can we redirect to plan page?
