### ISSUE TITLE
[ATS] Capture per customer metrics in Prometheus to support Public Beta

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#526]
For each customer (org) we want to track

- no. of repos where `codecov.yml` has `carryforward_mode : "labels"`
- If a static analysis report was sent for a given commit
- How many static analysis reports are being sent / customer
- no. of present-diff labels / commit / customer

**Comment by rohan-at-sentry** [comment]
It would work for me, I guess (although, I don't fully know what the benefit of emitting a statsd would be). Maybe @trent-codecov can elaborate

**Comment by giovanni-guidini** [comment]
We have (now) a few general metrics that let us know the general usage of static analysis and label analysis (not per customer, not per commit, just in general).

After much discussion adding per-customer, per-commit metrics to prometheus is not a good idea, and the way to go would be to use Timescale. But there are projects in place that might affect that.

So I was asked to hold on a little bit in making these changes.
They are not off the radar, just will hold on a little bit.
