### ISSUE TITLE
Investigate API Layer Improvement Opportunities

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#534]
Allocate time to evaluate our API layer, focusing on best practices, development speed, and codebase efficiency.

### Objectives
- Understand the current state of the API layer
- Pinpoint areas missing industry best practices
- Identify development bottlenecks
- Highlight codebase inefficiencies

### Note
Given the sprint's duration and the concurrent tasks, prioritize breadth over depth. The goal is to get a broad overview of areas needing attention rather than an exhaustive analysis.

### Deliverables
- A summarized Notion document with key findings
- Share findings with the team for review

**Comment by JerrySentry** [comment]
https://www.notion.so/sentry/Laundry-List-of-Improvements-Ideas-d8a09fd639874a45819daf533ea9b6f6

Discussed with Adrian and Scott as primary stakeholders of API, came up with a few relative low hanging fruits we can do now (made tickets for it), while other ones will need further discussions down the line
