### ISSUE TITLE
Add ATS to sentry repos

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#555]
- getsentry/sentry

In order to accomplish this, we need to have ATS output
1. List of tests to run
2. List of "skipped tests"

so that the sentry team can run ATS selected tests + non selected tests so that there is a gradual increase in confidence.

**Comment by giovanni-guidini** [comment]
TODO now
* write a job that runs every hour to collect the coverage we need in Sentry main branch
* also collect static analysis data
* also create commit and carry forward the reports
