### ISSUE TITLE
Investigate long load time on pulls page

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#648]
Investigate why load time is so long on the pulls page.

Context 👇 

<img width="585" alt="Screenshot 2023-10-04 at 12 46 07 PM" src="https://github.com/codecov/engineering-team/assets/129207373/98fd04d7-0a01-4839-af0e-75e3fe4e01a8">

<img width="582" alt="Screenshot 2023-10-04 at 12 46 44 PM" src="https://github.com/codecov/engineering-team/assets/129207373/1d29ea1e-a109-4422-b727-7ec32aa4092d">

link: https://app.codecov.io/gh/getsentry/sentry/pull/57084?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=getsentry

**Comment by RulaKhaled** [comment]
@katia-sentry screen shots are not shown any chance we can update them to help with the investigation? thank you

**Comment by RulaKhaled** [comment]
Can't reproduce page is working fine
