### ISSUE TITLE
Investigation slow queries when filtering coverage by flag

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#649]
The queries responsible for filtering coverage by flag are slow. The performance of these queries often falls within a 10-20 second range, which is long.

The aim of this investigation is to:
- Identify the root cause of the slowdown
- Propose solutions to optimize and improve the speed of the queries (in the comments of this issue)

**Comment by JerrySentry** [comment]
<img width="694" alt="Screenshot 2023-10-19 at 6 08 06 PM" src="https://github.com/codecov/engineering-team/assets/142266253/8a5a1b23-4d23-4c9b-85ba-5234d38e50b3">

using production server getting these numbers.
these are the endpoints affected by the flag filtering slow down.
