### ISSUE TITLE
Investigate ramifications on public api for the Lite plan

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#651]
This ticket is to investigate the public API access for users on our Lite plan. Without proper restrictions, there's an inherent risk that developers might use the API to construct functionalities that surpass the intended boundaries of the Lite plan. We want to make sure the public API does not provide users with more data than they would access in the UI. Investigation must take into account browser extensions and our Slack app.As we refine the public API's parameters for the Lite plan, our goal should be to find a sweet spot that upholds the plan's integrity while still offering developers and teams a seamless experience.

This investigation will cover various aspects of the API, including GraphQL resolvers, upload validation, and internal endpoints, to ensure that all areas are appropriately aligned with the restrictions and boundaries of the Lite plan.

context: 
- https://www.notion.so/sentry/Users-Lite-Plan-patch-only-c2ed9dc8955642caadef8d5c8563402b
- https://www.notion.so/sentry/Multiple-Tiers-40acddfc0968442b83a4c8b85c2720c7

Tasks
- Outline investigation findings in the comments and propose actions
- Feedback from team members

**Comment by JerrySentry** [comment]
The following endpoints will expose project coverage to Team users if called directly
- Public API
      - Branch Detail `/api/v2/github/codecov/repos/codecov-api/branches/main/`
      - Commit Detail `/api/v2/github/codecov/repos/codecov-api/commits/..`
      - Comparisons (all comparison endpoints) `/api/v2/github/codecov/repos/codecov-api/compare/..`
      - Coverage Trend `/api/v2/github/codecov/repos/codecov-api/coverage/..`
      - Commit Coverage Report `/api/v2/github/codecov/repos/codecov-api/pulls/`
      - Flags Coverage Trend
          - `/api/v2/github/codecov/repos/codecov-api/flags/unit/coverage/..`
      - Pull List
          - `/api/v2/github/codecov/repos/codecov-api/pulls/`
- Internal API
      - `/internal/github/codecov/repos/codecov-api/commits`
      - `/internal/github/codecov/repos/codecov-api/pulls`
      - `/internal/gh/codecov/codecov-api/commits`
      - `/internal/gh/codecov/codecov-api/compare/?base=..&head=..`
      - `/internal/gh/codecov/codecov-api/coverage/tree`
      - `/internal/gh/codecov/codecov-api/pulls`
      - `/internal/gh/codecov/repos`
- GraphQL API
    - `Coverage.totals: CoverageTotals`
    - `Repository.coverage`
