### ISSUE TITLE
Let API accept unauthenticated requests if coming from fork repos

### ISSUE THREAD

**Issue by dana-yaish** [codecov/engineering-team#736]
We can implement a low level auth class where it parses the request and identifies the repo based on the slug, branch and commit, check if PR is coming from a fork repo to an upstream one, and if upstream repo has ‘permit_forks’ mentioned before turned on. Then we can count it as authenticated. OR have the auth level identify it as anonymous repo, then when parsing the request have a validation step where it checks the just mentioned requirements.

**Comment by giovanni-guidini** [comment]
We're going with option 1: low level auth class that will check the tokenless claim before authenticating the request.
