### ISSUE TITLE
PR comment reports failed tests

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#886]
**Problem**
As a developer contributing code changes, it can be frustrating to navigate CI logs to investigate test failures that block a PR from being merged.

**Goal**
Provide an easy to digest report on the PR that gives the developer exactly the info they need to fix the PR so it can be merged

**Info to show **
1. List of test
2. Test failure reason

**More reading**
For an example of how we'll received and store test data (incl. failures and reasons of failures) see https://www.notion.so/sentry/Collection-of-Tests-Executed-bb6f8173c6284a158257df5c518babdf?pvs=4

Previous [design file](https://www.figma.com/file/mQ7Mc7dyF2eBbu6TrpGhLG/Failed-Test-Discovery?type=design&node-id=0%3A1&mode=design&t=Z4WUbYwQtWeba3yt-1) for [discovery issue](https://github.com/codecov/engineering-team/issues/480).

### Solution
The latest Figma [design file](https://www.figma.com/file/NSUtavgIRctCNpMGIXYh0c/GH-886?type=design&node-id=1-2&mode=design) 
Notion UX [note](https://www.notion.so/sentry/Failed-test-PR-comment-reports-UX-08a927af65164e4cac9883535b330179?pvs=4)

**Comment by Adal3n3** [comment]
UX review completed on 12/21. You can find the latest design on figma link below.

Figma: https://www.figma.com/file/NSUtavgIRctCNpMGIXYh0c/GH-886?type=design&node-id=1-2&mode=design
UX doc: https://www.notion.so/sentry/UX-Failed-test-PR-comment-reports-08a927af65164e4cac9883535b330179?pvs=4
