### ISSUE TITLE
Closing a gap between the onboarding/tutorial 

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#895]
### Problem to solve
Customer feedback: https://github.com/codecov/feedback/issues/18#issuecomment-1714900738

<img width="1313" alt="Screenshot 2023-12-05 at 10 35 58 AM" src="https://github.com/codecov/engineering-team/assets/152432831/1066074f-f57c-41d1-94ed-c6680f575281">

### Solve/Suggestion
Add a Learn more link to Get Started tutorial: https://docs.codecov.com/docs/quick-start
Note that we don't know where the customer will come in from so link back to the high level Quick-start page.

Figma [link](https://www.figma.com/file/A1m05f7t9TQjMSZkBqaSPY/GH-895?type=design&node-id=1-2&mode=design)

**Comment by Adal3n3** [comment]
UX reviewed on 12/13.

**Comment by RulaKhaled** [comment]
@Adal3n3 Are we expected to add the link to all /new page tabs or just GHA tab?

**Comment by Adal3n3** [comment]
@RulaKhaled Sorry that I didn't specific it on the design. We want to add the link to all/new page tabs because if they use other CI they don't need to read GHA tab.
